export const SIDE_DRAWER_OPEN = 'SIDE_DRAWER_OPEN';
export const SIDE_DRAWER_CLOSE = 'PRODUCT_LIST_CLOSE';
export const CART_DRAWER_CLOSE = 'PRODUCT_LIST_CLOSE';
export const CART_DRAWER_OPEN = 'PRODUCT_LIST_OPEN';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT';
export const CLEAR_CART = 'CLEAR_CART';
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS';
